import type { Project } from '@/types';

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: '产品摄影',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [
        {
          id: 'n1',
          type: 'image' as const,
          position: { x: 100, y: 100 },
          data: {
            label: '产品照片',
            imageUrl: null,
            width: 1024,
            height: 1024,
            format: 'png',
          },
          status: 'idle' as const,
        },
        {
          id: 'n2',
          type: 'text' as const,
          position: { x: 400, y: 100 },
          data: {
            label: '描述',
            content: '白色背景、柔光的专业产品照片',
          },
          status: 'idle' as const,
        },
      ],
      edges: [],
    },
  },
  {
    id: 'proj-002',
    name: '社交媒体营销',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [
        {
          id: 'n1',
          type: 'image' as const,
          position: { x: 100, y: 80 },
          data: {
            label: '主视觉横幅',
            imageUrl: null,
            width: 1920,
            height: 1080,
            format: 'png',
          },
          status: 'completed' as const,
        },
        {
          id: 'n2',
          type: 'image' as const,
          position: { x: 400, y: 80 },
          data: {
            label: '方形帖子',
            imageUrl: null,
            width: 1080,
            height: 1080,
            format: 'png',
          },
          status: 'idle' as const,
        },
        {
          id: 'n3',
          type: 'video' as const,
          position: { x: 100, y: 320 },
          data: {
            label: '宣传短视频',
            videoUrl: null,
            thumbnailUrl: null,
            duration: 15,
          },
          status: 'idle' as const,
        },
      ],
      edges: [
        {
          id: 'e1-2',
          source: 'n1',
          target: 'n2',
          type: 'process' as const,
          data: { operation: 'resize' },
        },
      ],
    },
  },
  {
    id: 'proj-003',
    name: '品牌视觉设计',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
  {
    id: 'proj-004',
    name: '视频分镜',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
  {
    id: 'proj-005',
    name: '纹理生成',
    thumbnail: null,
    owner_id: '1',
    team_id: 'team-001',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
  {
    id: 'proj-006',
    name: '角色概念图',
    thumbnail: null,
    owner_id: '1',
    team_id: 'team-001',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
];
