import type { Project } from '@/types';

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'Product Photography',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [
        {
          id: 'n1',
          type: 'image' as const,
          position: { x: 100, y: 100 },
          data: {
            label: 'Product Shot',
            imageUrl: null,
            width: 1024,
            height: 1024,
            format: 'png',
          },
          status: 'idle' as const,
        },
        {
          id: 'n2',
          type: 'text' as const,
          position: { x: 400, y: 100 },
          data: {
            label: 'Description',
            content: 'A professional product photo on white background with soft lighting',
          },
          status: 'idle' as const,
        },
      ],
      edges: [],
    },
  },
  {
    id: 'proj-002',
    name: 'Social Media Campaign',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [
        {
          id: 'n1',
          type: 'image' as const,
          position: { x: 100, y: 80 },
          data: {
            label: 'Hero Banner',
            imageUrl: null,
            width: 1920,
            height: 1080,
            format: 'png',
          },
          status: 'completed' as const,
        },
        {
          id: 'n2',
          type: 'image' as const,
          position: { x: 400, y: 80 },
          data: {
            label: 'Square Post',
            imageUrl: null,
            width: 1080,
            height: 1080,
            format: 'png',
          },
          status: 'idle' as const,
        },
        {
          id: 'n3',
          type: 'video' as const,
          position: { x: 100, y: 320 },
          data: {
            label: 'Promo Reel',
            videoUrl: null,
            thumbnailUrl: null,
            duration: 15,
          },
          status: 'idle' as const,
        },
      ],
      edges: [
        {
          id: 'e1-2',
          source: 'n1',
          target: 'n2',
          type: 'process' as const,
          data: { operation: 'resize' },
        },
      ],
    },
  },
  {
    id: 'proj-003',
    name: 'Brand Identity Design',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
  {
    id: 'proj-004',
    name: 'Video Storyboard',
    thumbnail: null,
    owner_id: '1',
    team_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
  {
    id: 'proj-005',
    name: 'Texture Generation',
    thumbnail: null,
    owner_id: '1',
    team_id: 'team-001',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
  {
    id: 'proj-006',
    name: 'Character Concept Art',
    thumbnail: null,
    owner_id: '1',
    team_id: 'team-001',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    canvas_data: {
      viewport: { x: 0, y: 0, zoom: 1 },
      nodes: [],
      edges: [],
    },
  },
];
